- index.php
Actually, this is more "technically correct" HTML. HTML and BODY elements are optional, a doctype is not.
> Unfix typo

- LBRY.class.php
Throw exceptions on error, check that we have results and always close the curl connection.
> API method fixes

- public/index.html
removed client-side template literals which are not supported in IE
> removed client-side template literals

- public/assets/css/style.css
- views/index.handlebars
- views/partials/documentation.handlebars
- views/partials/publish.handlebars
added a drag-and-drop zone for image selection
> publish tool update - added drag and drop

- views/allClaims.handlebars
- views/fourOhFour.handlebars
- views/index.handlebars
- views/noClaims.handlebars
- views/partials/topBar.handlebars
created a topBar partial for all handlebars pages to share
> all pages to share header

- views/index.handlebars
- views/partials/documentation.handlebars
- views/partials/examples.handlebars
- views/partials/publish.handlebars
I made 'examples' and 'publish' sections full horizontal sections.
> Style tweaks to homepage

- config/custom-environment-variables.json
- config/default.json
- config/development.json
- config/production.json
- config/test.json
- controllers/publishController.js
- controllers/serveController.js
- controllers/showController.js
- helpers/functions/getAllFreePublicClaims.js
- helpers/functions/isFreePublicClaim.js
- helpers/lbryApi.js
- helpers/lbryHelpers.js
- helpers/libraries/errorHandlers.js
- helpers/libraries/lbryApi.js
- helpers/socketHelpers.js
- models/file.js
- models/index.js
- package.json
- routes/api-routes.js
- routes/serve-routes.js
- routes/show-routes.js
- routes/sockets-routes.js
- server.js
- views/allClaims.handlebars
- views/index.handlebars
- views/partials/documentation.handlebars
- views/partials/examples.handlebars
- views/partials/publish.handlebars
- views/partials/topBar.handlebars
Added mysql table to track Files stored locally.  The serve routes now check the Files table before trying to perform a 'get' on the daemon.  If a local match is found based on claim_id, it checks the outpoint and either serves that local file or retrieves an updated one.
> mysql - record and check state of local files

- .eslintignore
- .eslintrc
- controllers/publishController.js
- controllers/serveController.js
- controllers/showController.js
- helpers/functions/getAllFreePublicClaims.js
- helpers/functions/isFreePublicClaim.js
- helpers/libraries/errorHandlers.js
- helpers/libraries/lbryApi.js
- models/file.js
- models/index.js
- package-lock.json
- package.json
- routes/api-routes.js
- routes/home-routes.js
- routes/serve-routes.js
- routes/show-routes.js
- routes/sockets-routes.js
- server.js
Edited code to be ES6, added eslint and some basic linting configuration, welcome 2017 syntax!
> Edited code to be ES6, added eslint and some basic linting configuration

- .eslintrc
- controllers/publishController.js
- controllers/serveController.js
- controllers/showController.js
- helpers/functions/getAllFreePublicClaims.js
- helpers/functions/isFreePublicClaim.js
- helpers/libraries/errorHandlers.js
- helpers/libraries/lbryApi.js
- models/file.js
- models/index.js
- routes/api-routes.js
- routes/home-routes.js
- routes/serve-routes.js
- routes/show-routes.js
- routes/sockets-routes.js
- server.js
Semicolon rule enforced as the main lbry-app uses semicolons!
> Semicolon rule added

- public/assets/css/allStyle.css
- public/assets/css/componentStyle.css
- public/assets/js/generalFunctions.js
- views/allClaims.handlebars
- views/layouts/main.handlebars
- views/partials/documentation.handlebars
- views/partials/examples.handlebars
- views/partials/whatIsSpeech.handlebars
created little open/close buttons for the homepage.  everything defaults to closed except publish.
> Front end collapse nav

- config/custom-environment-variables.json
- config/default.json
- config/development.json
- config/production.json
- config/test.json
- helpers/libraries/analytics.js
- helpers/libraries/publishHelpers.js
- routes/home-routes.js
- routes/serve-routes.js
- server.js
- made a change to how lbry addresses are added into the publish parameters. This is (fingers crossed) a temporary fix for the publishing bugs
- added some logging to help determine if ip addresses are coming from proxy (in progress towards fixing analytics)
> Separated pay, claim, and change wallet addresses

- config/production.json
- controllers/statsController.js
- routes/home-routes.js
- routes/serve-routes.js
- routes/show-routes.js
- updated the params sent to google analytics to ensure they send the info from client's request, rather than info from spee.ch.
- removed server side 'show' analytics because they were duplicative of what is embedded in the html sent to client.
> Analytics 3

- config/development.json
- routes/api-routes.js
- routes/sockets-routes.js
- views/partials/asset.handlebars
- views/partials/assetInfo.handlebars
- views/showLite.handlebars
- updated videos to stream and autoplay
> Support video

- config/development.json
- controllers/statsController.js
- helpers/libraries/errorHandlers.js
- models/file.js
- models/index.js
- models/request.js
- routes/api-routes.js
- routes/home-routes.js
- routes/serve-routes.js
- routes/show-routes.js
- routes/sockets-routes.js
- views/index.handlebars
- associated the File and Request tables (Files have many Requests, and Requests belong to one File)
- for 'trending images', created one sql query that handles joining and grouping the requests rather than sorting the data in js
> Trending images 2

- routes/home-routes.js
- views/index.handlebars
added trending images to homepage
> added trending images to homepage

- config/development.json
- public/assets/css/generalStyle.css
- public/assets/js/generalFunctions.js
- public/assets/js/index.js
- public/assets/js/memeFodder-publish.js
- public/assets/js/publishFunctions.js
- views/partials/assetInfo.handlebars
- views/partials/publish.handlebars
- views/show.handlebars
- for invalid inputs: removed alerts and replaced with bold, red text over the affected input
- on show routes: added focus to the text inputs when they are clicked
> Input validation

- config/development.json
- controllers/serveController.js
- controllers/statsController.js
- helpers/functions/getAllFreePublicClaims.js
- helpers/libraries/serveHelpers.js
- public/assets/css/componentStyle.css
- routes/serve-routes.js
- server.js
- views/partials/assetInfo.handlebars
- views/partials/trendingAssets.handlebars
- views/show.handlebars
- views/showLite.handlebars
- added ability to retrieve asset by first character of claim id
- updated show route to show short url
> Short urls

- public/assets/css/componentStyle.css
- public/assets/js/publishFunctions.js
- views/index.handlebars
- views/partials/publish.handlebars
- views/partials/trendingAssets.handlebars
- added 'Spee.ch/' before claim name input
> added 'Spee.ch/' before claim input

- public/assets/css/componentStyle.css
- public/assets/css/generalStyle.css
- public/assets/js/publishFunctions.js
- views/partials/topBar.handlebars
- increase image file size
- fixed typo
> updated file limit 10mb for images

- public/assets/css/componentStyle.css
- routes/api-routes.js
- speech.js
- views/layouts/show.handlebars
- views/partials/asset.handlebars
- views/partials/footer.handlebars
- views/partials/topBar.handlebars
- views/partials/trendingAssets.handlebars
- views/showLite.handlebars
- changed the way files are directly served to front end (changed api/streamFile to static /media folder)
- fixed trending images display (#118)
- fixed top bar so text resizes on different devices with media queries (#117)
> Media folder

- public/assets/css/generalStyle.css
- public/assets/js/generalFunctions.js
- public/assets/js/publishFunctions.js
- public/assets/js/validationFunctions.js
- views/index.handlebars
- views/partials/publish.handlebars
- views/partials/trendingAssets.handlebars
- updated input to warn of invalid characters as they are entered (#113)
- fixed claim name input so it would not reset cursor to the end of the input (#116)
- reorganized validation code a bit (#121)
> Client side input

- controllers/publishController.js
- helpers/publishHelpers.js
- public/assets/css/componentStyle.css
- public/assets/css/generalStyle.css
- routes/serve-routes.js
- routes/sockets-routes.js
- speech.js
- views/index.handlebars
- views/layouts/show.handlebars
- views/partials/assetInfo.handlebars
- views/partials/publish.handlebars
- views/partials/topBar.handlebars
- moved trending to separate page with nav link at top right
- added Title and Description fields (optional) to publish section
- added title and description fields to show route info
- added title and description to meta tags for open-graph / twitter
> Titles and descriptions

- views/channel.handlebars
> add url to channel browsing

- README.md
- config/custom-environment-variables.json
- config/default.json
- models/index.js
updated the mysql config variables
> reconfigured env variables and mysql connection

- config/custom-environment-variables.json
- config/default.json
- config/development.json
- config/loggerConfig.js
- config/production.json
- config/slackLoggerConfig.js
- controllers/statsController.js
- helpers/errorHandlers.js
- helpers/lbryApi.js
- helpers/serveHelpers.js
- models/index.js
- package.json
- speech.js
added `winston-slack-webhook` npm package and configured to send spee.ch logs to slack.
- error logs are being sent to #slack-errors
- info logs are being sent to #slack-logs
both are configurable in the `/config/production.json` file
> Slack messaging

- public/assets/css/general.css
- public/assets/css/mediaQueries.css
- public/assets/js/dropzoneFunctions.js
- public/assets/js/generalFunctions.js
- views/channel.handlebars
- views/index.handlebars
- views/partials/assetInfo.handlebars
- views/partials/channelCreationForm.handlebars
- views/partials/channelLoginForm.handlebars
- views/partials/navBar.handlebars
- views/partials/publishForm-Details.handlebars
- updated flex boxes & page widths
- updated pagination on channel page to only show as needed
> Redesign polish

- public/assets/css/general.css
- views/partials/navBar.handlebars
quick fix on nav bar vertical alignment
> fixed nav bar bottom alignment

- controllers/serveController.js
- controllers/statsController.js
- helpers/authHelpers.js
- models/certificate.js
- models/claim.js
- models/file.js
- models/index.js
- passport/local-login.js
- passport/local-signup.js
- routes/api-routes.js
- updated models to paramterize sql queries
> Sequelize queries

- helpers/sequelizeHelpers.js
- models/certificate.js
- models/claim.js
- routes/api-routes.js
updates based on @kauffj's input on https://github.com/lbryio/spee.ch/pull/234
> fixes to 234 based on JKs feedback

- .gitignore
- routes/serve-routes.js
- views/layouts/channel.handlebars
- views/layouts/main.handlebars
- views/layouts/show.handlebars
- views/partials/publishForm-Channel.handlebars
added meta descriptions for channel pages
> Channel metadata

- .gitignore
- routes/serve-routes.js
- this fixes `spee.ch/example` urls so they properly serve the 'show' page with meta tags for social sharing
> removed line causing serve on show route

- public/assets/css/general.css
- public/assets/css/mediaQueries.css
- views/showLite.handlebars
added proper class to constrain image to viewport size
> constrain to viewport on large images

- models/certificate.js
- models/claim.js
> switch to sequelize operator alias

- views/layouts/channel.handlebars
- views/layouts/embed.handlebars
- views/layouts/main.handlebars
- views/layouts/show.handlebars
- views/layouts/showlite.handlebars
@Smurphonomics what do you think?  I added an id to the body for each layout.
the layouts are as follows:
- main: general layout for homepage, about, login, 404, etc.
- channel: channel overview page
- show: layout for an asset displayed with details such as links and metadata
- showlite: layout for an asset served directly with no extra info/metadata
Is this going to be specific enough, or should we put an id on each view rather than at the layout level
> added id tags to body elements

- routes/serve-routes.js
- a quick not-so-dry patch, but this whole file is being refactored into smaller, reusable functions (DRY!) in the show-request-refactor branch for issue #214
> Serve image to embedded show urls

- controllers/publishController.js
- models/certificate.js
- models/claim.js
- models/request.js
- public/assets/js/publishFileFunctions.js
- routes/api-routes.js
- added check for timeout on response
> fix publishes hanging client side

- config/speechConfig.js.example
- helpers/errorHandlers.js
- helpers/handlebarsHelpers.js
- helpers/publishHelpers.js
- helpers/serveHelpers.js
- models/claim.js
- public/assets/js/assetConstructor.js
- public/assets/js/createChannelFunctions.js
- routes/api-routes.js
- routes/page-routes.js
- routes/serve-routes.js
- speech.js
- testpage.html
- views/embed.handlebars
- views/layouts/channel.handlebars
- views/layouts/main.handlebars
- views/partials/assetInfo.handlebars
- updated serve/show logic to show pages when requested by bots
- created a config file so site information like title and host could be set in one place and change based on environment (e.g. https://spee.ch for production, https://dev1.spee.ch for dev1).  This helps testing so links don't point to wrong server.
> 281 unfurl show links

- config/slackConfig.js
- models/claim.js
- models/index.js
- task-scripts/update-password.js
- changed 'publishing' to 'claim' in config file
- fixed a couple of areas where de-structuring would help the  config imports
> changed publishing to claim and updated config imports

- helpers/handlebarsHelpers.js
- models/claim.js
- moved open graph defaults from model layer to view layer
- added a check that truncates descriptions to 200 characters at most
> 304 truncate description

- models/claim.js
hot fix for an issue where the host was not getting passed with the claim info to the view
> updated model to add host data

- helpers/statsHelpers.js
- routes/api-routes.js
- views/partials/maintenanceBanner.handlebars
- views/partials/releaseBanner.handlebars
- moved stats functions from `controllers` to `helpers` folder because they are more general utility functions that controllers
- added a function to send google analytics timing events
- added google timing event to publish api route
> Track publish time

- helpers/googleAnalytics.js
- helpers/publishHelpers.js
- helpers/serveHelpers.js
- helpers/statsHelpers.js
- routes/api-routes.js
- routes/serve-routes.js
+ updated google analytics event and user timing actions
+ DRY'd up serve route code a little
+ added google analytics event actions to serve routes
> 295 - server-side GA events for tracking serve requests

- react/containers/Dropzone/index.js
- react/containers/Dropzone/view.jsx
- react/containers/PublishForm/index.js
- react/containers/PublishForm/view.jsx
- added dispatch of an action to clear file when a file with an error is selected
> 309 invalid video

- public/assets/css/general.css
- react/components/AssetDisplay/view.jsx
- react/components/ShowAssetLite/view.jsx
updated css for show page asset display
> 321 image overflows

- auth/authentication.js
- config/speechConfig.js.example
- controllers/publishController.js
- helpers/publishHelpers.js
- models/user.js
- passport/local-login.js
- react/containers/PublishUrlInput/view.jsx
- routes/api-routes.js
- task-scripts/update-password.js
- test/end-to-end/end-to-end.tests.js
- added the channel_id to the publish params
> Publish via channel id

- public/assets/css/general.css
- react/components/AssetInfo/view.jsx
- react/components/ShowAssetDetails/view.jsx
- added download link to asset details page
- removed some unneeded clutter on asset details page
> 326 add download link

- react/components/AboutPage/index.jsx
Add LBRY app download link to spee.ch content pages #377
> add download link

- config/speechConfig.js.example
- react/containers/PublishTool/index.js
- react/containers/PublishTool/view.jsx
- react/reducers/publish.js
added a config variable with which publishing can be disabled
> Publish disable config

- config/siteConfig.js
- config/slackConfig.js
- config/viewsConfig.js
- index.js
- server/controllers/api/claim/publish/createBasicPublishParams.js
- server/render/build/handlePageRender.js
- server/render/build/handleShowRender.js
- server/render/src/handlePageRender.jsx
- server/render/src/handleShowRender.jsx
Updated configs to separate the custom views.  Necessary to keep up with https://github.com/lbryio/www.spee.ch/pull/18
> Update configs to match www.spee.ch

- config/loggerConfig.js
- index.js
- server/lbrynet/index.js
- server/models/utils/createDatabaseIfNotExists.js
- high level error detection checks for lbrynet and retrieves wallet balance on startup
- removed confusing test of error log
- added a step to create the database if it was not already created
> Startup fixes

- client/build/containers/AssetInfo/view.js
- client/build/containers/ShowAssetLite/view.js
- client/src/containers/AssetInfo/view.jsx
- client/src/containers/ShowAssetLite/view.jsx
added a link to the lbry.io/get page on the pages where the assets are displayed
> added lbry.io/get link to asset show pages

- server/controllers/api/user/password/index.js
- server/routes/api/index.js
- added api route to allow for password reset via old password or master password in config
> Password reset

- client/build/containers/PublishDisabledMessage/view.js
- client/scss/all.scss
- client/scss/containers/_publish-disabled-message.scss
- client/src/containers/PublishDisabledMessage/view.jsx
- server/controllers/api/claim/publish/index.js
- server/controllers/api/config/site/publishing/index.js
- server/routes/api/index.js
added an api route to tell whether publishing is enabled or disabled
> Publishing configs route

- server/lbrynet/index.js
changing the timeout on `get` requests from 20 to 30 seconds
> updated timeout from 20 to 30 seconds

- index.js
- server/controllers/api/blocked/index.js
- server/models/utils/refreshBlockedList.js
- server/routes/api/index.js
updating startup flow to check and refresh the blocked list
> updated startup to refresh blocked list

- server/controllers/api/blocked/index.js
- server/controllers/api/claim/longId/index.js
- server/controllers/assets/utils/getClaimIdAndServeAsset.js
- server/models/blocked.js
- server/models/claim.js
- server/models/tor.js
- server/models/utils/refreshBlockedList.js
updated `blocked` table to use `outpoint` and keep all blocked claims
_note: requires dropping old blocked table prior to running this branch_
> Blocked timeout error

- client/build/components/AssetShareButtons/index.js
- client/build/components/ClickToCopy/index.js
- client/build/containers/AssetInfo/view.js
- client/src/components/AssetShareButtons/index.js
- client/src/components/ClickToCopy/index.jsx
- client/src/containers/AssetInfo/view.jsx
fixes bug where 'undefined' was showing up in social links rather than the claim name
> 505 twitter share undefined

- client/scss/components/_asset-display.scss
Fixes the error message issue shown in the below image.
> Error Message Fix

- client/scss/components/_asset-display.scss
Keeps content in view at any size.
> Keeps Content In View

- client/scss/components/_asset-display.scss
- client/scss/components/_page-layout-show-lite.scss
combining two of @Invariant-Change 's PRs related to the above issue.
> 518 large asset display

- server/controllers/api/claim/publish/index.js
update publish api response to include static embed url
> added embed url to api return

- client/build/components/DropzoneInstructionsDisplay/index.js
- client/scss/_variables.scss
- client/scss/components/_nav-bar.scss
- client/src/components/DropzoneInstructionsDisplay/index.jsx
a couple quick cosmetic fixes:
- reduce the padding on the top and bottom of the nav bar
- add some padding to the dropzone instructions and center them in the dropzone box
> nav bar spacing

- client/src/utils/metaTags.js
added the following tags
- twitter:image
- twitter:description
- twitter:title
> add twitter meta tags

- client/build/utils/metaTags.js
forgot to transpile the src on last PR
> build for client

- client/scss/components/_asset-display.scss
fix for images that are stretched too wide
> added object-fit and position to assets

- package-lock.json
- package.json
- server/utils/imageProcessing.js
removing this wrapper for imagemagick because it is not being used
> removed imagemagick npm package

- server/controllers/api/claim/get/index.js
only create File record if file is completed
> fix: ffprobe fails

- .gitignore
- README.md
- cli/configure.js
- cli/defaults/lbryConfig.json
- cli/defaults/loggerConfig.json
- cli/defaults/slackConfig.json
- fullstart.md
- package-lock.json
- package.json
- updated CLI to automatically add the user's ip address to configs.
- refactored file creation to one function and switched all config files to be defaults rather than keeping some in version control
> added node-ip and updated CLI

- server/index.js
> fixed embed view path. fixes #597

- client/src/components/ButtonPrimary/index.jsx
- client/src/containers/ChannelCreateForm/view.jsx
- client/src/containers/ChannelLoginForm/view.jsx
Now users can login/create channels with the enter key, instead of forcing them to click the enter button.
> allow form submit with enter key

- client/src/containers/AssetDisplay/view.jsx
- server/lbrynet/utils/handleLbrynetResponse.js
> fix error messages

- server/index.js
- server/routes/api/index.js
10 publishes in 10 minutes will result in an IP block, temporary solution out of critical necessity.
> Temporary anti-spam solution

- fullstart.md
Previous link was broken
New link: https://github.com/lbryio/spee.ch/blob/master/nginx_example_config
🎃
> Update link to nginx_example_config file

- cli/configure.js
- cli/defaults/siteConfig.json
- server/controllers/api/claim/publish/createPublishParams.js
- server/controllers/api/claim/publish/createThumbnailPublishParams.js
- server/lbrynet/index.js
https://github.com/lbryio/spee.ch/issues/609
> moves hardcoded bid amounts into siteConfig

- server/routes/index.js
This reverts commit 074e88b2680855eeb2818d35f14b9fc1fba5deb1.
> Revert "move pages to last in route order"

- README.md
- docs/ubuntuinstall.md
Adds gif, license, security to bring the project closer to standard.
> updates readme and install docs

- cli/configure.js
- package-lock.json
- package.json
- server/controllers/api/user/password/index.js
- server/index.js
- utils/createModuleAliases.js
Old behavior: siteConfig had some sensitive passwords.
New behavior: passwords are stored in ./config which is gitignored.
> moves sensitive keys to gitignored folder

- client/src/containers/AssetInfo/view.jsx
Users can now link to content on LBRY app and access info to use block explorer.
> adds LBRY and Permanent URLS to info component

- server/render/src/handleShowRender.jsx
Previously, 404 page sent 200 code. 
Now, 404 page and other bad claim requests send 404 code.
> Sets proper 404 status in most cases

- server/render/src/handleShowRender.jsx
Reverts lbryio/spee.ch#820
Insufficiently tested.
> Revert "Sets proper 404 status in most cases"

- docs/ubuntuinstall.md
Some expressed confusion at some of the wording in the ubuntu process. Also, the build process changed. This makes changes to address that.
> clarity changes to ubuntu docs

- server/utils/getClaimData.js
- webpack/webpack.client.config.js
> cuts staging from master

- .eslintignore
~8000 eslint errors down to ~250
> eslint now ignores server/bundle

- client/src/containers/AssetInfo/view.jsx
A youtube one for reference: 
<iframe width="560" height="315" src="https://www.youtube.com/embed/9qNPnlA4Ab4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
> fix iframe URL

- client/src/components/ChannelInfoDisplay/index.jsx
- client/src/containers/AssetBlocked/view.jsx
- client/src/containers/AssetDisplay/view.jsx
- client/src/containers/AssetInfo/view.jsx
- client/src/containers/Dropzone/index.js
- client/src/containers/NavigationLinks/view.jsx
- client/src/containers/SEO/view.jsx
- client/src/utils/createAssetMetaTags.js
- client/src/utils/createChannelMetaTags.js
- server/controllers/api/claim/publish/index.js
- server/controllers/api/claim/update/index.js
- server/index.js
- server/render/handleShowRender.jsx
- server/utils/getMediaDimensions.js
adds aliases
simplifies channel info heading
variable name changes
> minor changes

- client/src/containers/Dropzone/index.js
- client/src/utils/file.js
- server/controllers/api/claim/publish/parsePublishApiRequestFiles.js
This got closed accidentally and I couldn't reopen it.
> Rudimentary dropdown file errors

- README.md
> New repo owner

- client/src/containers/AssetDisplay/view.jsx
- client/src/containers/AssetInfo/view.jsx
- server/utils/getClaimData.js
Fixes outpoint logic and removes img tags from markdown descriptions
> small bugfixes to outpoint and tweak markdown

- client/scss/_asset-display.scss
- client/scss/_label.scss
- client/scss/_markdown.scss
- client/scss/_row.scss
- client/scss/_variables.scss
- client/src/components/FileViewer/index.jsx
- client/src/containers/AssetInfo/view.jsx
Labels info rows more like desktop app
skipsHTML (for now)
styles blockquotes
styles tables
styles paragraph margins
replaces broken css var()s
fixes some centering issues
styles images, controls their width
> improves markdown presentation

- cli/defaults/siteConfig.json
Mostly supports markdown settings.
Also begins to make setup more sane by specifying lbrynet home.
Also begins to support custom file extension overrides.
> adds some siteConfig settings for future use

- client/src/components/FileViewer/index.jsx
- client/src/containers/AssetInfo/view.jsx
disables html (e.g. <script>) in description and disallows 'image' tags in description by default
> makes final tweaks to markdown

- server/index.js
- server/lbrynet/index.js
wallet_balance no longer works.
> updates wallet_balance to account_balance

- client/src/components/PublishNsfwInput/index.jsx
- server/utils/getClaimData.js
* not yet shown in AssetInfo, etc
> enables nsfw updates

- customize.md
Updated this in a previous pull request but the way I phrased it was a little bit off. 
This provides the instructions that you must BUILD before STARTING the server for it to actually reflect the changes made.
> Updated the instructions to reflect building before starting

- README.md
- cli/defaults/siteConfig.json
- client/scss/_asset-display.scss
- client/scss/_markdown.scss
- client/src/components/ErrorBoundary/index.jsx
- client/src/components/FileViewer/index.jsx
- client/src/containers/AssetInfo/view.jsx
- docs/settings.md
links markdown settings to siteConfig
fixes some styling
> styling, markdown settings tied to config

- client/scss/_asset-preview.scss
- client/scss/_input.scss
- client/scss/_link.scss
- client/scss/_nav-bar.scss
- client/scss/_variables.scss
In setting up different staging environments and demos, it's good to have the site easily use the customer's branding colors.
> better enables style changes from variables file

- package-lock.json
- package.json
- server/controllers/assets/utils/getClaimIdAndServeAsset.js
- server/controllers/assets/utils/serveFile.js
- server/controllers/assets/utils/transformImage.js
querystrings containing h=#&w=# will scale the image.
querystrings containing an additional t=crop will crop to the center
system supports addition of more transformations responding to querystring vales as private functions inside transformImage.js
> implements querystring transformation

- server/controllers/api/claim/get/index.js
- server/utils/awaitFileSize.js
emergency fix for wait-on breaking
> replaces wait-on

- client/scss/_select.scss
- client/src/components/ChannelSelectDropdown/index.jsx
- client/src/components/PublishLicenseInput/index.jsx
- client/src/components/PublishLicenseUrlInput/index.jsx
- client/src/constants/publish_license_urls.js
- client/src/containers/AssetInfo/view.jsx
- client/src/containers/ChannelSelect/view.jsx
- client/src/containers/PublishMetadataInputs/index.js
- client/src/containers/PublishMetadataInputs/view.jsx
- client/src/pages/EditPage/view.jsx
- client/src/reducers/publish.js
- client/src/utils/publish.js
- server/chainquery/models/ClaimModel.js
- server/chainquery/queries/claimQueries.js
- server/controllers/api/channel/claims/getChannelClaims.js
- server/controllers/api/claim/publish/createPublishParams.js
- server/controllers/api/claim/publish/createThumbnailPublishParams.js
- server/controllers/api/claim/publish/index.js
- server/controllers/api/claim/publish/parsePublishApiRequestBody.js
- server/controllers/api/claim/update/index.js
- server/controllers/assets/utils/serveFile.js
- server/utils/getClaimData.js
- utils/createModuleAliases.js
Adds license, and if url, licenseUrl as a link to assetInfo. 
Adds licenseUrl and license to chainquery model
Adds licenseUrl to publish / edit form.
Populates license and licenseUrl from previous publish state
Tweaks select style
> Adds License and LicenseUrl to AssetInfo and Publish/Edit Forms

- docs/setup/conf/lbrynet/lbrynet.service.example
- docs/setup/conf/lbrynet/lbrynet.service.template
- server/lbrynet/index.js
changes download_directory to download_dir for sdk compatibility
also adds lbrynet.service examples for systemd
> updates lbrynet download_dir

- client/scss/_asset-preview.scss
- client/scss/_channel-claims-display.scss
- client/src/components/AssetPreview/index.jsx
To preview cards:
adds publish time information
rearranges label components
> improves preview cards

- server/controllers/api/claim/get/index.js
- server/utils/configureLogging.js
- server/utils/getClaimData.js
sets default timestamp setting to true
removes some unnecessary logger.infos or changes them to .error or .debug
logs get requests with useragent and claimid
> adds timestamp and relevance to logs

- server/controllers/api/claim/get/index.js
- server/utils/configureLogging.js
- server/utils/getClaimData.js
> Revert "adds timestamp and relevance to logs"

- client/src/components/AssetPreview/index.jsx
- package-lock.json
- server/controllers/api/claim/get/index.js
- server/controllers/api/claim/publish/index.js
- server/controllers/api/claim/publish/publish.js
- server/controllers/api/claim/update/index.js
- server/models/claim.js
- server/render/handleShowRender.jsx
- server/utils/configureLogging.js
fixes redirect promise error
adds timestamps to logs
moves some log levels from "info" to "verbose" or "debug"
removes unnecessary bot-induced lbrynet resolve
> improves quality and reduces noise in logs

- client/src/api/assetApi.js
- client/src/sagas/abandon.js
- server/controllers/api/claim/abandon/index.js
- server/lbrynet/index.js
Confirmed working locally. File/claims table has outpoint. Claim was abandoned by the sdk.
> fix: abandoning claims

- server/middleware/autoblockPublishMiddleware.js
adds ip whitelist capability
uses a /site/config/ipWhitelist.txt file
```
192.168.0.1
127.0.0.1
```
> adds ip whitelist

- cli/defaults/siteConfig.json
- server/index.js
- server/routes/api/index.js
Reverting previous changes and just opening cors on publish routes.
> applies open cors to publish routes

- client/src/containers/AssetInfo/view.jsx
+ pass claim id
Example: https://lbry.com/dmca/116d62d14d8efc311e1f8a9de92dcbc17deb259a
> Update report route

- server/chainquery/queries/claimQueries.js
Maybe fix the repost bug where a channel won't load for now.
> cut staging
