controllers/serveController.js, controllers/statsController.js, helpers/functions/getAllFreePublicClaims.js, helpers/libraries/errorHandlers.js, helpers/libraries/lbryApi.js, routes/serve-routes.js, routes/show-routes.js
This PR is to fix the issue described here:  https://github.com/lbryio/spee.ch/issues/61
Previously a lack of free, public claims was treated as an error.  However, the daemon was not actually returning an error or failing in any way.  Therefore, a lack of free, public claims will now be treated as a successful request that bore no results.
=> Dealing with lack of claims as a success

.gitignore, README.md, controllers/publishController.js, controllers/serveController.js, controllers/statsController.js, helpers/functions/getAllFreePublicClaims.js, helpers/libraries/errorHandlers.js, helpers/libraries/lbryApi.js, helpers/libraries/publishHelpers.js, models/file.js, public/assets/css/allStyle.css, public/assets/js/claimPublish.js, routes/api-routes.js
1. added a column to the mysql File table for 'address' to track which `address` is associated with each downloaded file
2. added an API route `/api/isClaimAvailable/:name`.  This route checks the mysql File table for matching `name`s, and if one is found it compares the address in the record with the spee.ch wallet's addresses to see if it was published via spee.ch.  The route returns a boolean.
3. before submitting a request to publish, the client checks the name availability via `/api/isClaimAvailable`.
4. added server side check on name availability before publish because (a) race condition during upload time and also because (b) publish requests coming from other sources (e.g. /api/publish) need to be checked as well.
=> Block used claims

routes/serve-routes.js, routes/show-routes.js, speech.js, views/layouts/show.handlebars
- added twitter card support for 'show' actions for images.  
- support for 'serve' actions will require a more invasive update in order to send html when twitter is trying to unfurl.
- support for unfurling gifs and videos will require applying to be white listed via twitter for Player Cards
=> Twitter card

controllers/showController.js, public/assets/css/componentStyle.css, routes/serve-routes.js, routes/show-routes.js, views/index.handlebars, views/partials/assetInfo.handlebars, views/partials/contribute.handlebars, views/partials/documentation.handlebars, views/partials/examples.handlebars, views/partials/learnMore.handlebars, views/partials/topBar.handlebars, views/partials/trendingAssets.handlebars, views/showLite.handlebars
- show routes are now naked urls such as `spee.ch/example` or `spee.ch/example/2`
- serve routes are now urls with file extensions, such as `spee.ch/example.jpg` or `spee.ch/example/2.jpg`
- made a few minor cosmetic changes, including help at top right and linking the content freedom flag to the relevant wiki
=> File extensions

helpers/functions/isFreePublicClaim.js, helpers/libraries/publishHelpers.js, views/partials/publish.handlebars
Add an additional license; licenses are stored in an array so that future modifications are simpler.
=> Add license cc attribution non commercial 4.0 international

routes/serve-routes.js, views/partials/asset.handlebars, views/partials/assetInfo.handlebars, views/showLite.handlebars
- added basic support to show .mp4 as .givf if the .gifv extension is used on direct spee.ch urls (spee.ch/[claimId]/example.gifv and spee.ch/[shortId]/example.gifv).
=> added basic support for showing .mp4 as .givf

controllers/serveController.js, controllers/statsController.js, helpers/constants.js, helpers/serveHelpers.js, models/certificate.js, public/assets/css/componentStyle.css, routes/page-routes.js, routes/serve-routes.js, views/allClaims.handlebars, views/channel.handlebars, views/layouts/main.handlebars, views/layouts/show.handlebars, views/new.handlebars, views/noChannel.handlebars, views/noClaims.handlebars, views/partials/assetInfo.handlebars, views/partials/topBar.handlebars
added support for channel resolutions
- resolves to a list of the channels assets:
- spee.ch/@channel
- spee.ch/@channel:shortid
- spee.ch/@channel:longclaimid
- resolves to a specific asset (show)
- spee.ch/@channel/name
- spee.ch/@channel:shortid/name
- spee.ch/@channel:longclaimid/name
- serves an asset
- spee.ch/@channel/name.ext
- spee.ch/@channel:shortid/name.ext
- spee.ch/@channel:longclaimid/name.ext
reorganized router functions
still to do: (will be a separate pr): add channel information to the asset's info page
=> Resolve channels

public/assets/js/generalFunctions.js
Firefox does not recognize the proprietary property 'event.srcElement'. The option to use event.target was added.
=> Proposed solution to isue 159 toggleSection in Firefox

views/about.handlebars
> Spee.ch is a media-hosting site that reads from and publishes content to the LBRY blockchain.
... reads slightly smoother than... 
> Spee.ch is a media-hosting site that reads and publishes content from the LBRY blockchain
=> Slightly better wording (from/to)

public/assets/css/general.css
Previously, the global video element was styled to make it look better on the stand alone page. However; the class `.showasset-light` is the video skin class assigned to the stand alone page only.
Based on this, I have optimised the style on this class and removed parts no longer needed from the `video-player` class, thereby not affecting any other pages for areas only required on the stand alone page.
=> general.css Video Skin Class Stlye Improvement

public/assets/css/general.css
A global property to wrap long words/numbers so they don't fall off the screen.
`word-wrap: break-word;`
=> Wrap Long Words

public/assets/css/general.css
Setting the logo link to use cursor pointer keeps things consistent with the use of user agent styling setting cursor pointer on Upload, Popular, and About links. Makes it more obvious that it's actually clickable.
=> Set logo link in navbar to use pointer cursor

config/speechConfig.js.example, test/end-to-end/end-to-end.tests.js
added an end-to-end test that publishes to a channel, in order to make sure in-channel publishing works and compare the response time for such publishes to non-channel publishes.
=> In-channel publish test

config/speechConfig.js.example, helpers/lbryApi.js
This fixes issue #324.
The LBRY is no longer hardcoded to localhost and is set by the config file. 
I haven't tested it. I ran into some problems while trying to install spee.ch locally on my computer.
=> Remove the hardcoded lbry API address

public/assets/css/general.css, react/components/PublishStatus/index.jsx, react/components/ShowAssetDetails/view.jsx, react/components/ShowAssetLite/view.jsx, react/containers/PublishForm/view.jsx
a couple patches from last merge into master:
- the publish tool was not being reset after a completed publish
- the asset was not being scaled to take the full width of its container on the details page
=> Patch publish tool reset and asset details css

helpers/googleAnalytics.js, helpers/lbryApi.js, routes/api-routes.js
in order to sharpen the google analytics surrounding events, I broke the events into two categories:
1. 'end-to-end' events which measure the time from receiving a request at the api endpoint to the time a response is issued to the client. (currently covers the publish api endpoint, with labels by file type)
2. 'lbrynet' events which measure the time from when a request is made to the daemon the time when the response is received from the daemon. (expanded these events with a label for each daemon action)
=> refactor(google analytics): split ga timing events into multiple categories

task-scripts/update-channel-names.js
This task retrieves all the Claim records that are missing the `channelName` field, and attempts to fill in the channel name based on the Claim's `certificateId`.
=> feat(task): wrote a task to fill in missing channel names

client/scss/components/_asset-preview.scss
Borders were accidentally added to video thumbs in a recent [PR](https://github.com/lbryio/spee.ch/pull/471/files). This removes them.
=> Border Removed From Video Thumbs

client/scss/components/_asset-display.scss
Video border was lost in recent [PR](https://github.com/lbryio/spee.ch/pull/471) This adds it back.
=> Adding Border Back to Videos

server/controllers/assets/utils/determineRequestType.js, server/middleware/torCheckMiddleware.js
changing social bot check back to an array instead of object, because the check needs to be non-exact.
in the below code, it only returns true if the user agent string is an exact match
```
const socialBotList = {
'facebookexternalhit': 1,
'Twitterbot': 1,
}
​
if (socialBotList[userAgent]) {
logger.debug();
return true;
} else {
return false;
}
```
in the below version, it will catch any string that contains the social bot name.  e.g. ` facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_u
atext.php)` or `Twitterbot/1.0`.  This will mean a change to `Twitterbot/2.0` or related will not require a change in this code.
```
const socialBotList = [
'facebookexternalhit',
'Twitterbot',
];
for (let i = 0; i < socialBotList.length; i++) {
if (userAgent.indexOf(socialBotList[i]) >= 0) { …
```
=> changed social bot list to array

client/build/components/AssetPreview/index.js, client/build/containers/AssetDisplay/view.js, client/src/components/AssetPreview/index.jsx, client/src/containers/AssetDisplay/view.jsx, server/controllers/api/claim/publish/parsePublishApiRequestFiles.js, server/controllers/api/claim/publish/validateFileTypeAndSize.js, server/controllers/assets/utils/serveFile.js, server/views/embed.handlebars
This PR fixes the issue where spee.ch was showing a page with a broken link instead of the asset.  This issues seems to have been a result of cloudflare caching the page document and serving that instead of the image or video. 
- added check for file name in publish request
- fixed accuracy of some file check error messages
- remove default content type of `image/jpeg` on file serving
- changed embeded assets to use the `spee.ch/asset/<name>/<claimid>` route which is specific for serving the asset itself, thus avoiding the confusion which lead to cloudflare serving the document from the cache
=> fix app thumbnail viewing on spee.ch

client/scss/components/_page-layout-show-lite.scss
Removing the marking fixes vertical alignment issues when using Flex.
=> Margin Breaks Flex Vertical Alignment

server/controllers/assets/serveByIdentifierAndClaim/index.js, server/controllers/utils/getClaimId.js, server/models/claim.js
updated `Claim.getClaimIdByLongChannelId` to reject with `NO_CLAIM` if a `claim id` is not found
=> updated Claim model to return proper error if no matching claim id found

server/controllers/api/claim/publish/publish.js, server/models/claim.js
A new spee.ch instance has no claims in its db so the max height is `NaN` which throws an error. This default value will be overridden when synced.
=> return default block height of 100000

client/src/utils/determineContentTypeFromExtension.js, server/models/claim.js
`image/jpg` was not a valid mime type; and we should favor `*.jpg` as used by common convention.
=> Fix content-type and file extensions (enforce image/jpeg and .jpg)

client/scss/all.scss, client/scss/social-share-link/_social-share-link.scss, client/src/components/AssetShareButtons/index.js, client/src/components/SocialShareLink/index.jsx
Addressing issue: https://github.com/lbryio/spee.ch/issues/608
Adding share to Mastodon button.
I can go on by adding share to Diaspora button and more, but it will make mobile view quite crowded & ugly. Desktop view is fine tho. 
Might require CSS Styling changes, which I'm not currently familiar with this project CSS.
Share to Diaspora btn:
```
<a
className='link--primary'
target='_blank'
href={`https://share.diasporafoundation.org/?title=${name}&url=${host}/${shortId}/${name}`}
>
diaspora
</a>
```
=> Add more Social Share links Addressing issue #608

client/scss/asset-preview/_asset-preview.scss, client/scss/channel-claims-display/_channel-claims-display.scss, client/src/components/AssetPreview/index.jsx, client/src/containers/ChannelClaimsDisplay/view.jsx, client/src/pages/ShowChannel/index.js, client/src/pages/ShowChannel/view.jsx
#603 
- remove channel info for multisite instances
- remove "grouping" of claims
- use grid for channel asset list display
- add title below thumbnail
=> Osprey landing page and styling

server/chainquery/queries/claimQueries.js
#638 added a filter for `bid_state: Controlling` claims
this PR updates the default query to claims that are `Controlling`, `Active`, or `Accepted`
=> update bid_state filter

server/controllers/api/channel/data/getChannelData.js, server/controllers/api/channel/shortId/index.js, server/controllers/api/claim/longId/index.js, server/controllers/utils/getClaimId.js
~~WIP, this is usable as-is, one known edge case does not work -> `/@channelName/claimName`~~
~~Channels load with and without ID's, claim pages require a channel ID present.~~
Should be working in full
=> Allow external channels to load via chainquery

client/src/containers/AssetInfo/view.jsx, server/controllers/pages/sendVideoEmbedPage.js, server/routes/pages/index.js, server/views/embed.handlebars, server/views/layouts/embed.handlebars, server/views/partials/logo.handlebars
Works and is usable and ready to merge, still working on final touches.
e.g.:
```
http://localhost:3000/video-embed/jiggytom/3023ed665a45361626f70375db616af074f314ab/pad:large,bottom,logoClaim:252e3c5137c076d4ea0786c0d418e965b5c1e9cf%2Fantimedia-logo
```
Supports:
- pad:{[small, medium, large]}
- bottom
- right
- logoClaim:{claimId}%2F{claimName}
- logoLink:{url}
Also has some player fixes to properly adjust sizing.  This should provide a much better embed experience.
=> Make configurable embeds

cli/configure.js
configure.js was destructuring channelClaimBidAmount incorrectly from the siteConfig. It is now moved to the proper place.
=> fixes missing amount at configure

server/routes/index.js
when visiting a page such as new or login at `spee.ch/${pageName}` it will treat the `pageName` as a claim and serve that; this PR fixes this problem
I don't know exactly why/how but it has something to do with object property ordering when the routes are imported from their respective files and put together with object spread
=> move pages to last in route order

server/render/build/handleShowRender.js, server/render/src/handleShowRender.jsx
Canonical URL forwarding throws an error when the saga does not put the asset data in the store
`TypeError: Cannot read property 'key' of undefined`
=> return null if either requestId or requestType are undefined

client/scss/_asset-preview.scss, client/src/components/AssetPreview/index.jsx
Old behavior: user had no way of seeing whether a link was a video.
New behavior: play button overlay, full opacity on hover.
Also updates AssetPreview styles to BEM naming convention.
=> adds playbutton overlay to videos

server/chainquery/bundle.js, server/chainquery/queries/claimQueries.js, server/controllers/api/channel/claims/getChannelClaims.js
This is a draft of a solution. 
1) What I'd like to do is have a central list of supported type strings ( 'image/jpg' ); passing this list allows for future filtering. Would it be better for supported types be passed or require()d?
2) Also, this function could be renamed or duplicated to GetAllMatchingChannelClaims, GetAllSupportedChannelClaims, or just GetChannelClaims. I don't think it makes sense to duplicate it just to get at currently unsupported content.
=> fixes blank tiles due to unsupported content

server/chainquery/bundle.js, server/chainquery/queries/claimQueries.js
Previous behavior:
Speech displayed results sorted only by height.
New behavior:
Speech displays results sorted by height, then claimID ascending.
Speech channel order matches lbry-desktop.
Will revisit when metadata contains date field.
=> standardizes channelClaimsArray order to match lbryumx sorting

client/src/containers/AssetInfo/view.jsx
Previous fix using id='short-link' caused copy button to copy contents of another element. This copies as intended.
=> fixes bug in lbryurl copy

client/src/containers/AssetInfo/view.jsx
label now says LBRY URI rather than ID for Robots
=> lbry uri copy label

server/render/handleShowRender.jsx
Previously, the 404 page responded with 200 code. 
Now it responds with 404 code when specifically the 'fallback' action from the /fallback controller exists.
Previously, an invalid claim such as /abcd/1234 responded with 200 code. Now it responds with a 404 code when canonicalUrl fails.
The home page and other redirects are unaffected.
=> app sends 404 code for /fallback and failing canonical

server/utils/getClaimData.js
Previous fix attempted to call split when file_name didn't exist such as on channel claims.
Code now checks for that.
Future not implemented yet: filenames without a . should have '' extension.
=> fixes channel claim issue introduced by file extension fix

server/controllers/api/channel/claims/getChannelClaims.js, server/utils/getClaimData.js
Previously, getChannelClaims would, already having a channelName and channelShortId, ask getClaimData to parse some data, and getClaimData was claling chainquery twice for channelName and channelShortId.   
Now, getClaimData has optional channelName and channelShortId params.
Loadin of minutephysics decreased from 12 seconds to under 4 seconds. Loading of FTL decreased from 25 seconds to under 5 seconds.
lbrynet get is no longer called during getChannelClaims; rather only once on loading actual content.
Please test.
=> reduces channel loadtimes, fixes fallback fileExt

cli/defaults/siteConfig.json, client/scss/_asset-preview.scss, client/src/components/AssetPreview/index.jsx, client/src/containers/AssetBlocked/index.js, client/src/containers/AssetBlocked/view.jsx, client/src/pages/ShowAssetDetails/view.jsx, server/controllers/api/claim/get/index.js, server/index.js, server/models/blocked.js, server/utils/blockList.js, server/utils/getClaimData.js
Visiting a content page shows an AssetBlocked component.
Visiting a component page still attempts to fetch() the file in order to elicit the 451 error.
I didn't want to send a 451 on document because document generally doesn't reload during normal navigation, and the document hangs on to the status throughout browsing. (This is also an issue for the 404).
Visiting a Channel page, until we redo pagination, Blocked content shows a customized 451 channel preview.
Blocklist is now in memory in a javascript Set() though I noticed no speed gains compared to local DB.
Blocklist Endpoint is now a configurable siteConfig.json -> details -> blockListEndpoint : "" parameter.
LBRY's blocklist is still the default configuration if blockListEndpoint is missing or null.
- three states of …
=> makes enhancements to dmca system

cli/defaults/siteConfig.json, client/src/components/DropzonePreviewImage/index.jsx, client/src/containers/Dropzone/view.jsx, client/src/utils/createAssetMetaTags.js, server/chainquery/models/ClaimModel.js, server/controllers/api/claim/publish/parsePublishApiRequestFiles.js, server/controllers/api/claim/publish/validateFileForPublish.js, utils/validateFileForPublish.js
This one will probably have breaking changes when deployed unless:
- site/custom/scss _variables is manually updated, and 
- cli/defaults/siteConfig is manually updated to /site/config/siteConfig 
Improvements made:
- more granular file size limit settings
- no more hardcoded type restrictions
- chainquery correctly assigns extensions in an extensible way
Todo: conditionally don't try to find file dimensions.
=> Refactor publish and validation and servability for all file types

server/controllers/api/claim/update/index.js, server/lbrynet/index.js
resolveUri presents `urls:` as a parameter instead of `uri:`
extraneous unsupported `sources:` field removed from publishParams[]
=> updates for sdk .32

client/src/containers/AssetInfo/view.jsx
Updated the download URL to retain the file extension. Before, when you would download the file it would not append the file extension, this will fix that.
=> Updated the download link to retain file extension.

README.md, cli/defaults/siteConfig.json, docs/settings.md, server/controllers/assets/utils/serveFile.js, server/utils/isValidQueryObj.js
Adds to documentation for url formats in readme
Assures that malicious users can't send arbitrarily large image requests.
Allows disabling or limiting the feature in settings.
=> documents and validates image resize

server/controllers/api/file/availability/index.js
Before, one instance of speech, already having a file entry in its database, would not check if another instance had updated the file. 
Now it does. We no longer use fileDB for availability in this case.
=> uses CQ-derived outpoint and file list to detect foreign file changes

client/src/channels/publish.js
Presently the spee.ch client will error out if it received an unexpected response, resulting in hangs and a very vague JSON parsing error. This failsafe will catch the known issue of server request size limits causing 413 responses if misconfigured, making things easier to diagnose, as well as catching any other unexpected responses cleanly. Further specific behaviours can be added to ensure administrators spend less time debugging simple configuration issues.
The 413 error response should be fairly self explanatory, sufficient to not need further documentation, though adding an addendum to the README.md would aid other developers have a smooth experience.
=> Added Server Response Error Handling

server/index.js, server/middleware/httpContextMiddleware.js
Niko found that the metrics table was 10G and we don't even use it.
=> stops logging metrics to localdb

package-lock.json, package.json
Reverts lbryio/spee.ch#1025
Seems to break staging.
server/models/certificate.js cannot find 'like' of undefined
Works without this bump
=> Revert "Bump sequelize from 4.41.1 to 5.3.0"

.travis.yml
Refer to https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration.
> In the next phase of the migration, all builds will run on virtual-machine-based infrastructure – regardless of the configuration for `sudo` in the `.travis.yml`.
> Soon we will run all projects on the virtual-machine-based infrastructure, the sudo keyword will be fully deprecated.
=> removed deprecated field in Travis
